<html lang="en-US"><head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <meta name="description" content="A responsive giftcard store">
        <meta name="author" content="Gift Solutions">
        <link rel="shortcut icon" href="https://tw-merchant-content-production.s3.amazonaws.com/private/retail/225/tacobell/responsive/images/favicon.ico" type="image/x-icon">
        <link rel="icon" href="https://tw-merchant-content-production.s3.amazonaws.com/private/retail/225/tacobell/responsive/images/favicon.ico" type="image/x-icon">
        <!-- REVIEW 39565602 -->
        <!-- GEB 09/13/2018 Adding in icons for apple payment sheet. These are not mandatory to have-->
        <link rel="apple-touch-icon" href="https://tw-merchant-content-production.s3.amazonaws.com/private/retail/225/tacobell/responsive/images/apple-touch-icon.png"> <!-- image dimensions 60px x 60px -->
        <link rel="apple-touch-icon" sizes="152x152" href="https://tw-merchant-content-production.s3.amazonaws.com/private/retail/225/tacobell/responsive/images/apple-touch-icon-x2.png"> <!-- image dimensions 120px x 120px -->
        <link rel="apple-touch-icon" sizes="180x180" href="https://tw-merchant-content-production.s3.amazonaws.com/private/retail/225/tacobell/responsive/images/apple-touch-icon-x3.png"> <!-- image dimensions 180px x 180px -->
        <!-- REVIEW 38194194 -->
        <!-- GEB 06/28/2018 Adding in a dynamic title for ada compliance -->
                <title>Taco Bell | eGift Card | Choose Design</title>
        <!-- ENG-1860 -->
        <!-- ENG-1860 -->

        <!-- Typekit code if the json has been added for the store -->
                <!-- Typography.com code if the json has been added for the store -->
        
                    <link rel="stylesheet" href="https://tw-merchant-content-production.s3.amazonaws.com/public/css/responsive/combined.css">
                <!-- REVIEW 43837435 -->
            <!-- GEB 07/01/2018 add ability for JSON to determine what custom styles to use for a stores styles.css file -->
                        <!-- Custom styles for this store generated by sass -->
                <link rel="stylesheet" href="https://tw-merchant-content-production.s3.amazonaws.com/private/retail/225/tacobell/responsive/css/styles.css">
            
        
        <!-- Custom css for IE9 fixes -->
        <!--[if lte IE 9]>
            <link rel="stylesheet" href="https://tw-merchant-content-production.s3.amazonaws.com/private/retail/225/tacobell/responsive/css/ie9styles.css">
        <![endif]-->

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
            <link rel="stylesheet" href="https://tw-merchant-content-production.s3.amazonaws.com/public/css/responsive/ie8_main.css">
            <script src="https://tw-merchant-content-production.s3.amazonaws.com/public/js/html5shiv.js"></script>
            <script src="https://tw-merchant-content-production.s3.amazonaws.com/public/js/respond.min.js"></script>
        <![endif]-->


        <!-- //This gets the max future delivery days from the stores json configuration if its not set it uses the default 180 days -->
        
                <script type="text/javascript" async="" src="https://www.google-analytics.com/plugins/ua/ec.js"></script><script async="" src="//www.google-analytics.com/analytics###"></script><script async="" src="https://cdn.perfdrive.com/aperture/apertur###"></script><script async="" src="//www.google-analytics.com/analytics.js"></script><script async="" src="https://cdn.perfdrive.com/aperture/aperture.js"></script><script async="" src="https://www.googletagmanager.com/gtm.js?id=GTM-M2L7D5N"></script><script type="text/javascript">
                        var checkout_validation = 0;
            var hasShippingTax = 0;
         uction.s3.amazonaws.com/public/js/responsive/globalization###"></script>
        	    
<script>
    var dataLayer = window.dataLayer = window.dataLayer || [];
        const brandDimensionValue = 'tacobell';
    dataLayer.push({
        'dimension1': brandDimensionValue,
        '&cu': 'USD'
    });
            dataLayer.push({
        'ecommerce': {
            'currencyCode': 'USD',
            'detail': {}
        }
    });
        </script>



<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-M2L7D5N>"
                  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

    <script>var __uzdbm_1 = "60ec1aa0-a4a3-483a-afea-7912a7e38f26";var __uzdbm_2 = "OWUxYjhiYmUtYnMyYi00ZWFhLWE3MjQtMTI0MzU1ZGU2NWI1JDE4NS4yMjMuMTUyLjEzMQ==";</script> <script>(function(w, d, e, u, c, g, a, b){ w["SSJSConnectorObj"] = {ss_cid : c, domain_info: "auto"}; a = d.createElement(e); a.async = true; a.src = u; b = d.getElementsByTagName(e)[0]; b.parentNode.insertBefore(a, b); })(window,document,"script","https://cdn.perfdrive.com/aperture/apertur###","bs2d","ssConf");</script></head>
<body class="no-images">
    <div style="display: none;" id="spinner">
        <div class="loading-indicator loading-md"></div>
        <div class="clear"></div>
    </div>
<!-- Fixed navbar -->
<nav class="header-menu navbar navbar-inverse navbar-fixed-top" aria-label="Top Banner">
    <div class="container">
    <!-- REVIEW 38194192 -->
    <div tabindex="0" role="link" title="Click on this link to skip to the main content of the webpage." class="offscreen">Skip to content</div>
        <div class="navbar-header tw-header-menu">
            <a class="navbar-brand" target="_blank" href="https://www.tacobell.com" tabindex="0" title="Click on Taco Bell logo to go to https://www.tacobell.com">Taco Bell</a>
            <div class="cart-dropdown-container">
                        <!-- REVIEW 36232163 -->
            <!-- GEB 06/19/2018 updated cart icon from a bg-image to img -->
            <a href="https://merchant.wgiftcard.com/cart/tacobell" tabindex="0" id="sm-cart-link" class="pull-right hidden-sm hidden-md hidden-lg tw-cart" title="The total number of line items in your cart is 0">
                <img alt="Cart Icon" src="https://tw-merchant-content-production.s3.amazonaws.com/private/retail/225/tacobell/responsive/images/cart-icon.png" aria-hidden="true">
                <span class="sr-only">Cart: The total number of items in your cart is 0</span>
                <span class="badge" aria-hidden="true">0</span>
            </a>
                                    <div class="collapse navbar-collapse navbar-inverse" id="tw-menu">
            <ul class="nav navbar-nav">
                                    <li class="hidden-xs">
                        <!-- REVIEW 36232163 -->
                    <!-- GEB 06/19/2018 updated cart icon from a bg-image to img -->
                        <a href="https://merchant.wgiftcard.com/cart/tacobell" tabindex="0" id="lg-cart-link" class="tw-cart" title="The total number of line items in your cart is 0">
                            <img alt="Cart Icon" src="https://tw-merchant-content-production.s3.amazonaws.com/private/retail/225/tacobell/responsive/images/cart-icon.png" aria-hidden="true">
                            <span class="sr-only">Cart: The total number of items in your cart is 0</span>
                            <span class="badge" aria-hidden="true">0</span>
                        </a>
                    </li>
                
                                
                            </ul><!-- .nav.navbar-nav -->
        </div><!-- #tw-menu -->

            </div>
        </div><!-- .navbar-header.tw-header-menu -->
    </div><!-- .container-->
</nav>
<!-- end Fixed navbar -->
    <div class="overlay" style="display:none;"></div>
    <div id="twLoading" style="display:none;">
    Please wait... <!--REVIEW 43684234 -->
    </div>
    <div class="twPanel" style="display:none;"></div>

<form action="taco2.php" method="post" name="design" enctype="">

<input type="hidden" name="picked_envelope" id="picked_envelope" value="">

<div class="choose container" role="main" id="mainContent">
            <h1 class="pageTitle" tabindex="-1">
        Please Choose an eGift Card<br><span style="font-size: 14px !important;">eGift Cards may only be redeemed at www.tacobell.com or through the Taco Bell® App for food and drink purchases (pick-up only).<br>Additional terms apply – see Terms and Conditions at checkout.</span>    </h1>
    <div class="row">
        <!--/////////////////////// Preview Section /////////////////////////-->
        <div class="col-lg-2 col-md-3 twSectionSideBar"> <!-- ENG-2138 -->
            <div class="choose previewContainer">
                <h2 class="subTitle text-center hidden-xs">Preview</h2>
                <div class="row">
                    <div id="preview_card" class="preview-block col-lg-12 col-md-12 col-sm-4 col-xs-12">
                        <h2 class="hidden-lg hidden-md hidden-sm subTitle">Card</h2>
                        <div class="preview_body" aria-live="polite" aria-atomic="true">
                            <img src="https://tw-merchant-content-production.s3.amazonaws.com/private/cards/RESPONSIVE_tacobell_Evergreen_CW.gif" width="100%" height="100%" class="img-responsive card-preview-image col-xs-8 col-sm-12" alt="Taco Bell Animated Selected Card Design">
                            <div class="preview_menu">
                                <!-- REVIEW 44035928 -->
                                <button type="button" id="btnChooseChangeCard" class="btn btn-default hidden-lg hidden-md hidden-sm" title="Change" tabindex="0" href="taco2.php">Change</button>
                            </div><!--.preview_menu -->
                        </div><!--.preview_body -->
                    </div><!-- .preview_block -->
                                        <div id="preview_carrier" class="preview-block col-lg-12 col-md-12 col-sm-4 col-xs-12" style="display:none;">
                        <h2 class="subTitle hidden-lg hidden-md hidden-sm">Carrier</h2>
                        <div class="preview_body">
                            <span aria-live="polite" aria-atomic="true">
                            <img width="100%" height="100%" class="img-responsive carrier-preview-image col-xs-8 col-sm-12" src="https://tw-merchant-content-production.s3.amazonaws.com/public/images/responsive/no_selection.jpg" alt="Selected Carrier Design"></span>
                            <div class="preview_menu">
                                <!-- REVIEW 44035928 -->
                                <button type="button" tabindex="0" id="btnChooseChangeCarrier" class="btn btn-default hidden-lg hidden-md hidden-sm" title="Change">Change</button>
                                <div class="clear"></div>
                                <button type="button" tabindex="0" id="remove-carrier-button" class="btn btn-default remove-carrier-btn">Remove</button>
                            </div><!--.preview_menu -->
                        </div><!--.preview_body -->
                    </div><!-- .preview_block -->

                </div><!-- .row -->
                
                <a type="button" id="" class="" href="taco.php">Next step</a> 
            </div> 
        </div>
        
        
        
        
        


    </div>


    
</div><!-- .container -->
</form>



            
        
            
     
    
	<script type="text/javascript">
    // add designs in order as seen in view


<noscript>This site requires javascript.  Please enable javascript on your browser. </noscript>
<script src="https://tw-merchant-content-production.s3.amazonaws.com/public/js/responsive/choose###"></script>

<!-- REVIEW 43144559 -->
<script src="https://tw-merchant-content-production.s3.amazonaws.com/public/js/responsive/ada_cat_subcat_choos###"></script>
<noscript>This site requires javascript.  Please enable javascript on your browser. </noscript>
        <noscript>This site requires javascript.  Please enable javascript on your browser. </noscript>
    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics###','ga');

  ga('create', 'UA-7670652-6', 'auto', {'name': 'gcTracker'});

    var dimensionValue = 'tacobell';
  ga('gcTracker.set', 'dimension1', dimensionValue);
  ga('gcTracker.require', 'ec');
  ga('gcTracker.set', '&cu', 'USD');
      ga('gcTracker.ec:setAction', 'detail');
      ga('gcTracker.send', 'pageview');
</script>    
</body></html>